# Generated by Django 6.0.4 on 2026-04-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_api', '0004_userprofile_designation_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='seniority',
            new_name='experience_level',
        ),
    ]
