# Generated by Django 6.0.4 on 2026-04-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_api', '0005_rename_seniority_userprofile_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='source',
            field=models.CharField(choices=[('MANUAL_PAUSE', 'Manual Pause'), ('MANUAL_STOP', 'Manual Stop'), ('AUTO_STOP_8PM', 'Auto Stop 8PM')], default='MANUAL_STOP', max_length=20),
        ),
    ]
