# Generated by Django 6.0.4 on 2026-04-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_api', '0006_alter_timelog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='milestone_docs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/'),
        ),
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='task_docs/'),
        ),
    ]
