# Generated by Django 6.0.4 on 2026-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms_api", "0010_task_estimated_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
