# Generated by Django 5.2.9 on 2026-06-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_api', '0023_projectdeadlinechangerequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectdeadlinechangerequest',
            new_name='pms_api_pro_project_1a81d5_idx',
            old_name='pms_api_pro_project_8a1f0d_idx',
        ),
    ]
