services:
  web:
    build: .
    container_name: pms-web
    ports:
      - "${APP_PORT:-6009}:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py ensure_superuser &&
             python manage.py runserver 0.0.0.0:8000"
